### ISSUE TITLE
Package for Bower

### ISSUE THREAD

**Issue by aanev** [dverbovyi/angular-heremaps#13]
Currently angular-heremaps provides npm package and is published on https://www.npmjs.com/. However, as long as it is an angular and not node.js specific package I was thinking that it would be more appropriate to make it available via Bower.

https://bower.io/docs/creating-packages/

What do you think?

Thanks!

**Comment by dverbovyi** [comment]
No, bower is outdated. All packages exist in NPM

Since 2015 I have stop seeing bower in projects I worked/was involved in or just popular repositories I've used.

The good proof in this article https://gofore.com/stop-using-bower/
