### ISSUE TITLE
Calculate coordinates with screen to geo

### ISSUE THREAD

**Issue by tatarski** [dverbovyi/angular-heremaps#15]
Hi,
I am curious to know whether there is currently any way to convert event click coordinates (x, y) to map coordinates (latitude and longitude)?

*edit Also would you accept help with writing the wiki page?

Thanks in advance

**Comment by dverbovyi** [comment]
Hi @tatarski , thank you for interesting in this project.

I will add soon this requested feature directly into directive API, but now you can use the official HereMaps API to do that. You just need to retrieve map instance from directive api, and customize for itself, e.g:

https://github.com/dverbovyi/angular-heremaps/wiki/customizing
https://developer.here.com/api-explorer/maps-js/v3.0/infoBubbles/position-on-mouse-click
    
```
//your controller
 /**
 * An event listener is added to listen to tap events on the map.
 * Clicking on the map displays an alert box containing the latitude and longitude
 * of the location pressed.
 * @param  {H.Map} map      A HERE Map instance within the application
 */
function setUpClickListener(map) {
  // Attach an event listener to map display
  // obtain the coordinates and display in an alert box.
  map.addEventListener('tap', function (evt) {
    var coord = map.screenToGeo(evt.currentPointer.viewportX,
            evt.currentPointer.viewportY);
    alert('Clicked at ' + Math.abs(coord.lat.toFixed(4)) +
        ((coord.lat > 0) ? 'N' : 'S') +
        ' ' + Math.abs(coord.lng.toFixed(4)) +
         ((coord.lng > 0) ? 'E' : 'W'));
  });
}
 
$scope.onMapReady = function(api){
     var mapInstance = api.getPlatform().map;
    
    setUpClickListener(mapInstance)
}
```


   ```
//html template
 <div heremaps controls events
         options="mapOptions"
         places="markers" 
         map-ready="onMapReady">
    </div>
```

**Comment by tatarski** [comment]
Thank you for your time
