### ISSUE TITLE
Instancing from H

### ISSUE THREAD

**Issue by tatarski** [dverbovyi/angular-heremaps#16]
Hi,
At a place in my code i want to set the maps view bounds. To do so I'm doing:
`var boundingBox = new H.geo.Rect(...);`
Is there any way to create such an instance without having to call the heremaps API directly ?

**Comment by dverbovyi** [comment]
Hi, @tatarski 
The **setViewBounds** method available on map-ready callback

```
$scope.onMapReady = function(api){
    var bounds = new H.geo.Rect(42.3736,-71.0751,42.3472,-71.0408)
    
    api.setViewBounds(bounds);
}
```
```

<div heremaps 
     ...
      map-ready="onMapReady">
 </div>
```

**Comment by tatarski** [comment]
I was actually asking if there is a way to create a 'bounds' object through your API. I don't want my application to instance bounds through `new H.geo.Rect(...)` . I know it's some minor issue but making a call to `H` directly draws back on code quality.

**Comment by dverbovyi** [comment]
@tatarski I've got you point. I will implement your requested feature soon. Also, any pull requests are welcomed)

**Comment by dverbovyi** [comment]
@tatarski I've added your requested changes. Please, take a look https://github.com/dverbovyi/angular-heremaps/releases/tag/v0.1.7

NPM version is up to date as well
