### ISSUE TITLE
Support geo shapes

### ISSUE THREAD

**Issue by joakimglaving** [dverbovyi/angular-heremaps#22]
Hello, it would be great if this directive had support for geo shapes: https://developer.here.com/documentation/maps/topics/spatials.html

Is this something you will be adding? Or maybe it's possible already but I am blind? :)

Best regards,
x42y

**Comment by dverbovyi** [comment]
Hi @x42y 

Thanks for the interesting in this project.

I've added your requested feature to the backlog of things that have to be done.

Currently, you can add shapes using direct map instance like;

```
$scope.onMapReady = function(heremaps) {
    var circle = new H.map.Circle({lat: 52.51, lng: 13.4}, 8000);
    heremaps.map.addObject(circle);
}
```
