### ISSUE TITLE
UpdateMarkers  and Calculate Route example

### ISSUE THREAD

**Issue by aliexalter** [dverbovyi/angular-heremaps#7]
Hi, Can you please submit updateMarkers and Calculate route function syntax. Thanks

**Comment by aliexalter** [comment]
I have a $timeout function in which I want to add Markers to random locations. I have push the marker to $scope.markers and call $scope.map.updateMarkers(); but it removed my previous marker. Your help will be appreciated. Kind regards

**Comment by dverbovyi** [comment]
@aliexalter , Thank you for reporting an issue

yes, `updateMarkers` removes all existing markers and replaces with new ones.
Currently if it's blocker for you, you can grab all your markers in new array and pass them into `updateMarkers(markers, refreshViewbounds)`, where `markers` - array with all your markers, and `refreshViewbounds` - boolean flag to update view bounds according to markers position

I will add your requested feature soon and provide better docs

**Comment by dverbovyi** [comment]
@aliexalter according to calculate-route syntax please take a look on this example

https://github.com/dverbovyi/angular-heremaps/blob/gh-pages/js/app.module.js

demo is [here](https://dverbovyi.github.io/angular-heremaps/)
