### ISSUE TITLE
directive on marker bubble

### ISSUE THREAD

**Issue by jirawatp** [dverbovyi/angular-heremaps#9]
Hi,

I would like to used directive eg. myDirect , ng-src in marker bubble.

Could you suggest how can i win on this?

Thanks

**Comment by dverbovyi** [comment]
Hi, @jirawatp 

You need to compile your directive before passing it to the markers array, 
e.g you have your markers in scope

```
$scope.markers = [
            {
                pos: { lat: 25.1075831, lng: 55.1461 },
                popup: {
                    display: 'onHover',
                    markup: $compile('<myDirect></myDirect')(scope);
                }
            }
]
```

and then pass your markers to the heremaps-directive like this

```
<div class="map" 
            heremaps 
            controls="right-bottom" 
            options="mapOptions" 
            events="listeners" 
            places="markers" 
            map-ready="onMapReady">
        </div>
```

**Comment by jirawatp** [comment]
Hi @dverbovyi ,

Thank you for your help. I will try this ASAP.
